services:
  # Node.js Backend
  - type: web
    name: predictacare-backend
    env: node
    buildCommand: export NODE_ENV=development && cd frontend && npm install && npm run build && cd ../admin && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && NODE_ENV=production npm start
    envVars:
      - key: NODE_VERSION
        value: 18

  # Python Flask Prediction Service
  - type: web
    name: predictacare-ml
    env: python
    rootDir: backend
    buildCommand: pip install setuptools && pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
