services:
  # Node.js Backend
  - type: web
    name: predictacare-backend
    env: node
    buildCommand: export NODE_ENV=development && cd frontend && npm install && npm run build && cd ../admin && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && NODE_ENV=production npm start
    envVars:
      - key: NODE_VERSION
        value: 18

  # Python Flask Prediction Service
  - type: web
    name: predictacare-ml
    env: python
    rootDir: backend
    buildCommand: |
      python3.10 -m pip install --upgrade pip setuptools wheel
      python3.10 -m pip install -r requirements.txt
    startCommand: python3.10 server.py
