services:
  - type: web
    name: node-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run server

  - type: web
    name: python-ml
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py

  - type: web
    name: frontend
    env: node
    rootDir: frontend
    buildCommand: npm install
    startCommand: npm run dev

  - type: web
    name: admin
    env: node
    rootDir: admin
    buildCommand: npm install
    startCommand: npm run dev
